package com.ni.demos;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONArray;
import com.alibaba.fastjson.JSONObject;
import com.ni.entity.FlinkJobInfo;
import lombok.AllArgsConstructor;
import lombok.Data;

/**
 * @ClassName FastJsonTest
 * @Description todo
 * @Author zihao.ni
 * @Date 2023/6/25 18:12
 * @Version 1.0
 **/
public class FastJsonTest {
    private static final String FLINK_JOB_INFO =
            "{\"jid\":\"4e2279c7097e86d4331db82bbe692743\",\"name\":\"x2_1710748757562\",\"isStoppable\":false,\"state\":\"RUNNING\",\"start-time\":1710748784134,\"end-time\":-1,\"duration\":68235516,\"maxParallelism\":128,\"now\":1710817019650,\"timestamps\":{\"FAILED\":0,\"FAILING\":0,\"FINISHED\":0,\"CREATED\":1710748784251,\"RUNNING\":1710748785027,\"CANCELED\":0,\"SUSPENDED\":0,\"RECONCILING\":0,\"RESTARTING\":0,\"INITIALIZING\":1710748784134,\"CANCELLING\":0},\"vertices\":[{\"id\":\"cbc357ccb763df2852fee8c4fc7d55f2\",\"name\":\"Source: TableSourceScan(table=[[default_catalog, default_database, source_table_for_metric]], fields=[num]) -> Calc(select=[CAST(metric_result_table((metric_source_table(num) * 2))) AS num]) -> Sink: Sink(table=[default_catalog.default_database.result_table], fields=[num])\",\"maxParallelism\":128,\"parallelism\":5,\"status\":\"RUNNING\",\"start-time\":1710748794878,\"end-time\":-1,\"duration\":68224772,\"tasks\":{\"CANCELED\":0,\"RECONCILING\":0,\"DEPLOYING\":0,\"INITIALIZING\":0,\"CANCELING\":0,\"CREATED\":0,\"RUNNING\":5,\"FINISHED\":0,\"SCHEDULED\":0,\"FAILED\":0},\"metrics\":{\"read-bytes\":0,\"read-bytes-complete\":true,\"write-bytes\":0,\"write-bytes-complete\":true,\"read-records\":0,\"read-records-complete\":true,\"write-records\":0,\"write-records-complete\":true}}],\"status-counts\":{\"CANCELED\":0,\"RECONCILING\":0,\"DEPLOYING\":0,\"INITIALIZING\":0,\"CANCELING\":0,\"CREATED\":0,\"RUNNING\":1,\"FINISHED\":0,\"SCHEDULED\":0,\"FAILED\":0},\"plan\":{\"jid\":\"4e2279c7097e86d4331db82bbe692743\",\"name\":\"x2_1710748757562\",\"nodes\":[{\"id\":\"cbc357ccb763df2852fee8c4fc7d55f2\",\"parallelism\":5,\"operator\":\"\",\"operator_strategy\":\"\",\"description\":\"Source: TableSourceScan(table=[[default_catalog, default_database, source_table_for_metric]], fields=[num]) -&gt; Calc(select=[CAST(metric_result_table((metric_source_table(num) * 2))) AS num]) -&gt; Sink: Sink(table=[default_catalog.default_database.result_table], fields=[num])\",\"optimizer_properties\":{}}]}}                                                                         ";

    public static void main(String[] args) {
        //String string = parseArray("[{\"tagId\":13,\"enumIds\":[38,39,40,41,42,43]}]").toString();
        //System.out.println(string);

        FlinkJobInfo flinkJobInfo = JSON.parseObject(FLINK_JOB_INFO, FlinkJobInfo.class);
        //System.out.println(flinkJobInfo);

        System.out.println(JSON.parseArray(mertics, FlinkMetric.class));

    }


    public static JSONArray parseArray(String arrayString) {

        return JSON.parseArray(arrayString);
    }

    /**
     * 使用JSON.parseObject解析JSON ARRAY 无法解析成功
     *
     * @param arrayString
     * @return
     */
    public static JSONObject parseObjectFromArrayString(String arrayString) {
        return JSON.parseObject(arrayString);
    }

    private static String mertics =
            "[{\n" +
                    "\t\"id\": \"0.numBytesInRemotePerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.incoming-byte-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.topic.ABC.partition.0.currentOffsets\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.partition-revoked-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.commit-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].join-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].successful-reauthentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.successful-reauthentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].io-wait-time-ns-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.request-size-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.incoming-byte-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-throttle-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numRecordsInPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].connection-creation-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].failed-reauthentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.successful-authentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.heartbeat-response-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.request-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commit-id\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBuffersInRemotePerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.io-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].numRecordsOut\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.connection-creation-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-size-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.buffers.inputExclusiveBuffersUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.failed-rebalance-rate-per-hour\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.failed-authentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.records-per-request-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.connection-creation-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBytesInLocal\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].bytes-consumed-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.network-io-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].partition-revoked-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].records-lead-min\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].connection-creation-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.batch-split-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.io-waittime-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].reauthentication-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.buffer-available-bytes\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.start-time-ms\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].join-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.Buffers.inputQueueLength\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.request-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesOutPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesInRemote\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.busyTimeMsPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].numRecordsInPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].io-time-ns-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commit-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commitsFailed\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.count\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-error-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.connection-close-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBuffersInRemotePerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].records-lag-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.batch-size-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.partition-assigned-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.iotime-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.join-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBuffersOut\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.response-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.records-consumed-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].records-per-request-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.commit-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesInLocalPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.successful-reauthentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBytesInRemote\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.buffers.outPoolUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.poll-idle-ratio-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].rebalance-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].heartbeat-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].assigned-partitions\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.reauthentication-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-send-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].response-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.reauthentication-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].rebalance-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.current-offsets.ABC-0\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].time-between-poll-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].connection-count\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].join-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.rebalance-latency-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].successful-reauthentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).numRecordsOut\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-throttle-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.successful-authentication-no-reauth-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.last-poll-seconds-ago\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].rebalance-latency-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.failed-authentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.connection-creation-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.version\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].partition-lost-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.successful-reauthentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.request-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].failed-rebalance-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].incoming-byte-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.records-lag-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.iotime-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-retry-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].request-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.bytes-consumed-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Output.Buffers.outputQueueLength\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).currentInputWatermark\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.batch-split-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-queue-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.io-wait-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].records-consumed-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].sync-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].join-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].partition-revoked-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].last-rebalance-seconds-ago\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.outgoing-byte-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.select-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].sync-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBuffersInLocalPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-size-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.connection-close-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.Buffers.inputExclusiveBuffersUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBuffersInLocal\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.io-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.io-wait-time-ns-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.topic.ABC.partition.0.committedOffsets\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.commit-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.io-wait-time-ns-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.connection-count\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.bufferpool-wait-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.buffers.inputQueueLength\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].records-consumed-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).currentOutputWatermark\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.request-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBytesInRemotePerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.isBackPressured\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].request-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.bufferpool-wait-time-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.last-heartbeat-seconds-ago\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesInPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.failed-rebalance-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.records-per-request-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.reauthentication-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].io-wait-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBytesInLocalPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].select-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.sync-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.network-io-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numRecordsIn\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].network-io-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.produce-throttle-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.request-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.connection-close-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.metadata-age\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBuffersInRemote\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].sync-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBuffersOutPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.outgoing-byte-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.outgoing-byte-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.successful-reauthentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).numRecordsOutPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBuffersInLocalPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.commit-id\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.failed-reauthentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.response-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.assigned-partitions\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].network-io-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.buffer-exhausted-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].rebalance-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.failed-authentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].version\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].failed-authentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.rebalance-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].time-between-poll-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.sync-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.io-waittime-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.outgoing-byte-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numRecordsOut\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.select-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-size-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-queue-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.backPressuredTimeMsPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.numBuffersInRemote\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.io-time-ns-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.partition-lost-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].heartbeat-response-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].partition-assigned-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.sync-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.time-between-poll-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.committed-offsets.ABC-0\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.select-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.incoming-byte-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-error-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.compression-rate-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.buffer-total-bytes\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].partition-lost-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.idleTimeMsPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.Buffers.inPoolUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).numRecordsInPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.join-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.failed-reauthentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.successful-authentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].outgoing-byte-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].request-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.commit-id\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.rebalance-rate-per-hour\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.join-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.last-rebalance-seconds-ago\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].sync-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].currentOutputWatermark\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].io-waittime-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.connection-creation-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].iotime-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.join-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].heartbeat-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commit-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].successful-authentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].count\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.successful-authentication-no-reauth-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.produce-throttle-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].numRecordsOutPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].failed-reauthentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].successful-authentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.request-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].start-time-ms\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).numRecordsIn\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.request-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.buffers.inputFloatingBuffersUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].request-size-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Output.Buffers.outPoolUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.failed-authentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].last-poll-seconds-ago\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].rebalance-rate-per-hour\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.io-time-ns-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.io-wait-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.response-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].successful-authentication-no-reauth-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.waiting-threads\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-retry-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.heartbeat-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.rebalance-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.commit-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-throttle-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.network-io-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.incoming-byte-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.select-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesIn\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.fetch-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.checkpointStartDelayNanos\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.partition-lost-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.records-consumed-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.records-lead-min\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.request-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].connection-close-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].last-heartbeat-seconds-ago\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.rebalance-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.time-between-poll-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.failed-reauthentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.network-io-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.partition-assigned-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].reauthentication-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.buffer-exhausted-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.buffers.outputQueueLength\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.buffers.inPoolUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.requests-in-flight\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.heartbeat-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.sync-time-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].partition-assigned-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].failed-rebalance-rate-per-hour\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].poll-idle-ratio-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.partition-revoked-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.bytes-consumed-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-latency-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.successful-authentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.response-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].connection-close-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.count\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numRecordsOutPerSecond\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.reauthentication-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.start-time-ms\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Shuffle.Netty.Input.Buffers.inputFloatingBuffersUsage\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesOut\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.version\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-send-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.record-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBytesInLocal\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commitsSucceeded\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.failed-reauthentication-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.successful-authentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.batch-size-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].fetch-throttle-time-avg\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].bytes-consumed-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].KafkaConsumer.connection-close-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].incoming-byte-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].numRecordsIn\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commit-latency-max\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].failed-authentication-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].commit-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].io-ratio\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].outgoing-byte-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.numBuffersInLocal\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].select-rate\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Source__TableSourceScan(table=[[default_catalog__default_database__source_table].response-total\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.connection-count\"\n" +
                    "}, {\n" +
                    "\t\"id\": \"0.Sink__Sink(table=[default_catalog_default_database_result_table]__fields=[ad]).KafkaProducer.request-size-avg\"\n" +
                    "}]";
}

@Data
@AllArgsConstructor
class Student {
    private String name;
    private Integer age;
    private Student childStudent;
}

class FlinkMetric {
    private String id;

    @Override
    public String toString() {
        return "FlinkMetric{" +
                "id='" + id + '\'' +
                '}';
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}